---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: hobson
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.1.4
        ports:
        - containerPort: 4222
        - containerPort: 8222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: hobson
spec:
  selector:
    app: nats
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 4222
    - name: management
      protocol: TCP
      port: 8222
